name: Test

permissions:
  contents: read  # required for actions/checkout@v3
  actions: read

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install lint Python
        run: ./.github/scripts/precommit-install.sh
      - name: Lint Python
        run: ./.github/scripts/precommit-lint.sh
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: test-image
          tags: |
            type=schedule
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: build
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Load test
        run: .github/scripts/docker-test-action.sh
      - uses: 8398a7/action-slack@v3
        with:
          author_name: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          job_name: "Test"
          status: ${{ job.status }}
          fields: ref,message,workflow,job,took,author
          mention: subteam^S03KPC0D63V # @devops
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: failure() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
